name: "GDY-MettaGrid"

report_stats_interval: 100
normalize_rewards: false

sampling: 0
desync_episodes: true

game:
  # Required list of inventory items
  inventory_item_names:
    - ore_red
    - ore_blue
    - ore_green
    - battery_red
    - battery_blue
    - battery_green
    - heart
    - armor
    - laser
    - blueprint

  num_agents: 64
  obs_width: 11
  obs_height: 11
  num_observation_tokens: 200
  max_steps: 1000

  # Global observation tokens configuration
  global_obs:
    episode_completion_pct: true
    last_action: true
    last_reward: true
    resource_rewards: false

  # Show recipe inputs in observations for all converters
  recipe_details_obs: false

  agent:
    default_resource_limit: 10
    resource_limits:
      heart: 255
    freeze_duration: 10
    action_failure_penalty: 0.0
    
    rewards:
      inventory:
        heart: 1
      stats: {}

  groups:
    agent:
      id: 0
      sprite: 0
      props: {}

  objects:
    altar:
      type_id: 8
      input_resources:
        battery_red: 3
      output_resources:
        heart: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 0

    wall:
      type_id: 1
      swappable: false

    block:
      type_id: 14
      swappable: true

    mine_red:
      type_id: 2
      output_resources:
        ore_red: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 0

    mine_blue:
      type_id: 3
      color: 1
      output_resources:
        ore_blue: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 0

    mine_green:
      type_id: 4
      output_resources:
        ore_green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 0

    generator_red:
      type_id: 5
      input_resources:
        ore_red: 1
      output_resources:
        battery_red: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 0

    generator_blue:
      type_id: 6
      input_resources:
        ore_blue: 1
      output_resources:
        battery_blue: 1
      color: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 0

    generator_green:
      type_id: 7
      input_resources:
        ore_green: 1
      output_resources:
        battery_green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 0

    armory:
      type_id: 9
      input_resources:
        ore_red: 3
      output_resources:
        armor: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 0

    lasery:
      type_id: 10
      input_resources:
        ore_red: 1
        battery_red: 2
      output_resources:
        laser: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 0

    lab:
      type_id: 11
      input_resources:
        ore_red: 3
        battery_red: 3
      output_resources:
        blueprint: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 0

    factory:
      type_id: 12
      input_resources:
        blueprint: 1
        ore_red: 5
        battery_red: 5
      output_resources:
        armor: 5
        laser: 5
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 0

    temple:
      type_id: 13
      input_resources:
        heart: 1
        blueprint: 1
      output_resources:
        heart: 5
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 0

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: true
    get_items:
      enabled: true
    attack:
      enabled: true
      consumed_resources:
        laser: 1
      defense_resources:
        armor: 1
    swap:
      enabled: true
    change_color:
      enabled: false
    change_glyph:
      enabled: false
      number_of_glyphs: 4

  map_builder:
    _target_: metta.mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    border_width: 6

    room:
      _target_: metta.mettagrid.room.random.Random
      width: 64
      height: 64
      border_width: 0

      agents: 64

      objects:
        mine_red: 128
        generator_red: 64
        altar: 32
        armory: 0
        lasery: 0
        lab: 0
        factory: 0
        temple: 0
        wall: 0
